name: pre_flutter
description: 设计工作室PRE管理系统
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.9.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.5
  file_picker: ^6.2.1
  flutter_easyloading: ^3.0.5
  community_charts_flutter: ^1.0.2
  url_launcher: ^6.2.2
  permission_handler: ^10.4.0
  adaptive_dialog: ^1.1.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  go_router: ^17.2.3
  retrofit: ^4.9.2
  logger: ^2.7.0
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.15.0
  json_serializable: ^6.11.2
  riverpod_generator: ^4.0.0+1
  retrofit_generator: ^10.2.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
